name: Code Review

on:
  pull_request:
    branches: [ main ]

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: ChaoticRoman/gpt-code-review-action@v9
        with:
          model: 'o3-mini'
          openai-key: ${{ secrets.OPENAI_API_KEY }}
          max-length: 50000
