name: Ruff

on:
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ruff
        uses: chartboost/ruff-action@v1.0.0
        with:
          args: check -v --show-source .
